[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nyc-taxi"
version = "0.1.0"
description = "NYC TLC Taxi end-to-end data pipeline"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
include = ["nyc_taxi*"]
